## Part A - Vectorized Programming with NumPy
### Task 1 - Arrays, Statistics, and Indexing
● Generate Array A with 100 random integers. Set a random seed for reproducibility.
● Use NumPy functions to find min, max, median, mean, and standard deviation of Array A.
● Generate Array B with exactly 100 values using np.arange().
● Implement np.zeros() and np.ones(). Display shape and data type.
● Implement np.linspace(). Briefly state how it differs from np.arange().
● Create one 2D and one 3D array. Show shape, ndim, indexing, rows, columns, and slicing.
● Use reshape() to create a matrix, then flatten it back to 1D.


In [21]:
import numpy as np
np.random.seed(42) 
A = np.random.randint(1, 101, 100)
print("Array A:")
print(A)

Array A:
[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22  53   2  88
  30  38   2  64  60  21  33  76  58  22  89  49  91  59  42  92  60  80
  15  62  62  47  62  51  55  64   3  51   7  21  73  39  18   4  89  60
  14   9  90  53   2  84  92  60  71  44   8  47  35  78  81  36  50   4
   2   6  54   4  54  93  63  18  90  44  34  74  62 100  14  95  48  15
  72  78  87  62  40  85  80  82  53  24]


In [22]:
print("Minimum:", np.min(A))
print("Maximum:", np.max(A))
print("Median:", np.median(A))
print("Mean:", np.mean(A))
print("Standard Deviation:", np.std(A))

Minimum: 2
Maximum: 100
Median: 54.0
Mean: 51.54
Standard Deviation: 29.278463074417004


In [23]:
B = np.arange(1, 101)

print("Array B:")
print(B)
print("Number of values:", len(B))

Array B:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Number of values: 100


In [24]:
zeros_array = np.zeros((2,4)) #creates an array containing zeros.
ones_array = np.ones((2,4)) #creates an array containing ones.
print("Zeros Array:")
print(zeros_array)
print("Shape:", zeros_array.shape)
print("Data Type:", zeros_array.dtype)

print("\nOnes Array:")
print(ones_array)
print("Shape:", ones_array.shape)
print("Data Type:", ones_array.dtype)

Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (2, 4)
Data Type: float64

Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape: (2, 4)
Data Type: float64


In [25]:
C = np.linspace(1, 100, 10)

print("Array C using linspace:")
print(C)

Array C using linspace:
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [26]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("2D Array:")
print(array_2d)

print("Shape:", array_2d.shape)
print("Number of dimensions:", array_2d.ndim)

print("Element at row 1, column 2:", array_2d[1, 2])
 
print("First row:", array_2d[0, :])
 
print("Second column:", array_2d[:, 1])
 
print("First two rows:")
print(array_2d[0:2, :])

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Number of dimensions: 2
Element at row 1, column 2: 6
First row: [1 2 3]
Second column: [2 5 8]
First two rows:
[[1 2 3]
 [4 5 6]]


In [27]:
array_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print("3D Array:")
print(array_3d)

print("Shape:", array_3d.shape)
print("Number of dimensions:", array_3d.ndim)
 
print("Element at [0, 1, 2]:", array_3d[0, 1, 2])
 
print("First block:")
print(array_3d[0])
 
print("First row of first block:")
print(array_3d[0, 0, :])
 
print("All blocks, first row:")
print(array_3d[:, 0, :])

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Number of dimensions: 3
Element at [0, 1, 2]: 6
First block:
[[1 2 3]
 [4 5 6]]
First row of first block:
[1 2 3]
All blocks, first row:
[[1 2 3]
 [7 8 9]]


In [28]:
numbers = np.arange(1, 13)

print("Original 1D Array:")
print(numbers)
 
matrix = numbers.reshape(3, 4)

print("\nReshaped Matrix:")
print(matrix)
 
flattened = matrix.flatten()

print("\nFlattened Array:")
print(flattened)

Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Task 2 - Vectorized Arithmetic and Linear Algebra
● Create two matrices. Perform addition, element-wise multiplication, and matrix multiplication using @
or np.matmul().
● For a square matrix, find its transpose and determinant.
● If invertible, find the inverse and verify A @ A^-1 using np.allclose().
● Use vectorized NumPy operations; avoid explicit Python loops.


In [29]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]


In [30]:
addition = A + B

print("A + B:")
print(addition)

A + B:
[[ 6  8]
 [10 12]]


In [31]:
elementwise_multiplication = A * B

print("A * B:")
print(elementwise_multiplication)

A * B:
[[ 5 12]
 [21 32]]


In [32]:
matrix_multiplication = A @ B

print("A @ B:")
print(matrix_multiplication)



A @ B:
[[19 22]
 [43 50]]


In [33]:
# Transpose of A
A_transpose = A.T

print("Transpose of A:")
print(A_transpose)

Transpose of A:
[[1 3]
 [2 4]]


In [34]:
# Calculate determinant of A
det_A = np.linalg.det(A)

print("Determinant of A:", det_A)

# Find inverse of A
A_inverse = np.linalg.inv(A)

print("Inverse of A:")
print(A_inverse)

# Verify A @ A^-1 gives the identity matrix
verification = A @ A_inverse

print("A @ A^-1:")
print(verification)

print("\nIs A @ A^-1 approximately equal to identity matrix?")
print(np.allclose(verification, np.eye(2)))

Determinant of A: -2.0000000000000004
Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]
A @ A^-1:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Is A @ A^-1 approximately equal to identity matrix?
True
